Prevent apt update warnings
The following error is displayed when 

sudo apt update

Error: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://apt.postgresql.org/pub/repos/apt focal-pgdg InRelease' doesn't support architecture 'i386'

Need to change
deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main

to
deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt focal-pgdg main